version: '3.9'
services:
  mongoDb:
    image: mongo:5.0
    restart: always
    container_name: task-mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?err}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?err}
      MONGO_DATABASE: ${MONGO_DATABASE:?err}
      MONGO_PORT: ${MONGO_PORT:?err}


 